### PR TITLE
patch for #4

### PR DESCRIPTION
**Pull request by abma**
also added .travis.yml config file for compile test.

### CODE REVIEW

**Comment by abma** [comment]
@robertmassaioli 

*bump* anything wrong with the pull request?

**Comment by robertmassaioli** [comment]
I don't have too much time to spend on this. I'm going to just trust that it works on all operating systems still. Somebody will raise an issue if it does not.

**Comment by abma** [comment]
> Thankyou for notifying me about this. I don't work very much on this project but if you turned it into a pull request too then it would save me time and I would accept it.

... you didn't accept it :-(

**Comment by abma** [comment]
ok, thanks! :)

**Comment by robertmassaioli** [comment]
I decided to check if it would build on OSX first. It does not. No vdpau support on the latest OSX it seems. So this has become a non issue. Merged. :)

**Pull request merged**
